### ISSUE TITLE
Cannot find module 'deep-extend'

### ISSUE THREAD

**Issue by ibrodev** [YenePay/yenepay.sdk.nodejs#1]
after installing all the required dependency modules for sample shop application and try to run the application it brakes with can't find module 'deep-extend' error. 
![yenepay issue](https://user-images.githubusercontent.com/32592590/52633008-2a5a0d80-2ed4-11e9-9018-816793ae841e.PNG)

**Comment by airmax-7** [comment]
The missing module references are now added to package.json of the sample shop application. Pull the latest commit and you should be good to go.

**Comment by ibrodev** [comment]
@airmax-7 
it solves the problem Thanks
