### ISSUE TITLE
Sandbox UserName and password are not available 

### ISSUE THREAD

**Issue by deresegetachew** [YenePay/yenepay.sdk.nodejs#2]
I was testing the sample application and when I click on the pay with yenepay button it redirects me to the login page (https://login.sandbox.yenepay.com/identity/login?signin=4d20f4a038e3e1a04c6810412b74f046). In you documentation it is mentioned the sandbox details are found in the community page https://community.yenepay.com/docs/getting-started/ but that page is empty.

also the page about how to setup sandbox account is also down
https://community.yenepay.com/docs/sandbox/how-to-setup-sandbox-account/

**Comment by kaleabmelkie** [comment]
Did some search in the documentation of [community.yenepay.com](https://community.yenepay.com), and found this: [community.yenepay.com/docs/yenepay-sandbox/how-to-create-sandbox-users](https://community.yenepay.com/docs/yenepay-sandbox/how-to-create-sandbox-users/)

It basically says to go to [sandbox.yenepay.com](https://sandbox.yenepay.com) and generate your own test account.

But a better documentation (perhaps, at least in the [README](https://github.com/YenePay/yenepay.sdk.nodejs/blob/master/README.md)) would be nice.

**Comment by SisayKelkle** [comment]
Good we are glad to hear that everything is working for you. Hope you find it easy integrating your app with YenePay using our android SDK.

Thank you for all the helpful feedbacks you gave us. We are working on better documenting and adding even more samples to all our GitHub repositories.

Here at YenePay we would love to learn more about your App/Services so please tell us more about it. If it is available we can let our customers know about your system as well. Also please let us know any thoughts you have about our service.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
